name: AI Code Review

on:
  pull_request:
    branches: [master]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Review This Pull Request
        run: |
          curl --location 'https://careersupport.serveblog.net/api/code-review' \
          --header 'X-API-TOKEN: ${{ secrets.CAREER_SUPPORT_API_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "githubToken": "${{ secrets.PERSONAL_GITHUB_TOKEN }}",
            "repositoryName": "${{ github.repository }}",
            "prNumber": ${{ github.event.pull_request.number }}
          }'
